disabled_rules:
  - weak_delegate

excluded:
  - Carthage

function_parameter_count:
  warning: 6

line_length:
  warning: 150
  error: 250

type_name:
  min_length:
    error: 1
  max_length:
    warning: 50
    error: 100
