language: swift

os:
  - linux
  - osx

osx_image: xcode9.2

cache:
  bundler: true
  directories:
    - Carthage

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle exec fastlane dependencies; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle exec fastlane test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift test; fi
