matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic

    - os: osx
      osx_image: xcode9.2
      language: swift

      env:
        - LANE=test_ios

      cache:
        bundler: true
        directories:
          - Carthage

    - os: osx
      osx_image: xcode9.2
      language: swift

      env:
        - LANE=test_tvos

      cache:
        bundler: true
        directories:
          - Carthage

    - os: osx
      osx_image: xcode9.2
      language: swift

      env:
        - LANE=test_macos

      cache:
        bundler: true
        directories:
          - Carthage

    - os: osx
      osx_image: xcode9.2
      language: swift

      env:
        - LANE=test_watchos

      cache:
        bundler: true
        directories:
          - Carthage

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      bundle install;
      bundle exec fastlane dependencies;
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    fi

script:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      bundle exec fastlane $LANE;
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      swift test;
    fi
